print(f"A literal like \"True\" is a string type.")
print(f"A literal like {False} is a bool type.")
print(f"A literal like {(1, 2, 3)} is a tuple type.")
print(f"A literal like {1.5} is a float type.")
print(f"A literal like {[1, 2, 3]} is a list type.")
print(f"A literal like {2} is an int type.")
print(f"A literal like {range(5)} is a range type.")
print(f"A literal like {{1, 2, 3}} is a set type.")
print(f"A literal like {None} is a none type.")
print(f"A literal like {{'foo': 'bar'}} is a dict type.")